on: push
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: planetariumhq/ninechronicles-headless-metrics-aggregator:git-${{ github.sha }}
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: login
        run: docker login --username '${{ secrets.DOCKER_USERNAME }}' --password '${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}'
      - name: build
        run: docker build . -t ${{ env.DOCKER_IMAGE }}
      - name: push
        run: docker push ${{ env.DOCKER_IMAGE }}
